# Environment: ${environment}
# Generated by Terraform

# Application Settings
NODE_ENV=staging
PORT=8080
LOG_LEVEL=info

# Database Settings
REDIS_URL=redis://${redis_username}:${redis_password}@${redis_endpoint}
REDIS_USERNAME=${redis_username}
REDIS_PASSWORD=${redis_password}

# Search Settings
MEILISEARCH_URL=${meilisearch_endpoint}
MEILISEARCH_API_KEY=${meilisearch_master_key}

# Repository Settings
GITHUB_REPOSITORY=${github_repo}

# Other Configuration
DEBUG=false
ENABLE_ANALYTICS=true