aws_region          = "us-east-1"
environment         = "dev"
environment_version = "1.0.0"
redis_username      = "backend"
redis_password      = "9supply-Available7-Eddie-detach-Neigh-4lath-Spruce-abrasive-Zeppelin3"
meilisearch_master_key = "FdK7sP2xV9nL4qRbT6cY8eZ3wJmA5hGu"
github_repo         = "git@github.com:luchox-dev/qleber-platform.git"